[workspace]
members = [
    "dapla_client",
    "dapla_common",
    "dapla_server",
    "dapla_wasm",
    "dapla_yew",
    "examples/echo/client",
    "examples/echo/server",
    "examples/notes/client",
    "examples/notes/common",
    "examples/notes/server",
]

[profile.release]
lto = true
