[workspace]
members = [
    "dapla_client",
    "dapla_server",
    "dapla_wasm",
    "examples/hello/client",
    "examples/hello/server",
]

[profile.release]
lto = true

# https://github.com/Lymia/enumset/issues/17
[patch.crates-io.enumset_derive]
git = "https://github.com/ocboogie/enumset"
branch = "span-fix"
